- name: Convert and Deploy
  if: steps.changes.outputs.changed_files != ''
  run: |
    set -e
    echo "Starting conversion and deployment..."

    IFS=',' read -ra FILES <<< "${{ steps.changes.outputs.changed_files }}"

    for FILE in "${FILES[@]}"; do
      echo "----------------------------------------"
      echo "Processing file: $FILE"

      if [ ! -f "$FILE" ]; then
        echo "❌ Markdown file not found: $FILE"
        continue
      fi

      TXT_FILE="${FILE%.md}.txt"
      echo "Converting $FILE to $TXT_FILE"
      cp "$FILE" "$TXT_FILE"

      FOLDER=$(dirname "$FILE")
      REPO_NAME=$(basename "$FOLDER")

      DEST_REPO="https://x-access-token:${{ secrets.COOL_README_TOKEN }}@github.com/CoolPluginsTeam/${REPO_NAME}.git"
      TEMP_DIR="temp-${REPO_NAME}"

      echo "Cloning destination repo: $DEST_REPO"
      if ! git clone --depth 1 --branch temp_branch "$DEST_REPO" "$TEMP_DIR"; then
        echo "❌ Failed to clone repo: $DEST_REPO"
        continue
      fi

      echo "✅ Cloned into: $TEMP_DIR"
      cp "$TXT_FILE" "$TEMP_DIR/$(basename "$TXT_FILE")" || {
        echo "❌ Failed to copy $(basename "$TXT_FILE")"
        continue
      }

      cd "$TEMP_DIR"
      git config user.name "github-actions"
      git config user.email "actions@github.com"

      git add "$(basename "$TXT_FILE")"
      if git diff --cached --quiet; then
        echo "ℹ️ No changes to commit."
      else
        git commit -m "Update $(basename "$TXT_FILE") from .md source"
        echo "✅ Committed changes."
        if git push origin temp_branch; then
          echo "✅ Pushed to temp_branch."
        else
          echo "❌ Push failed for $REPO_NAME"
        fi
      fi

      cd ..
      rm -rf "$TEMP_DIR"
      echo "✅ Cleaned up $TEMP_DIR"
      echo "----------------------------------------"
    done
